hardwares:

  - hwspi:
      name: "spi-0"
      number: 32766
      chipselect: 0
      speed: 100000
      mode: 1 # CPOL=1 and CPHA=1

  - uart:
      name: "uart-0"
      devpath: "/dev/ttyUSB0"
      baudrate: 115200
      rtscts: false
      dsrdtr: false
      read_timeout: 1
      write_timeout: 1

  - uart:
      name: "tcpuart-0"
      devpath: "rfc2217://turing-coffee-client"
      baudrate: 57600
      rtscts: false
      dsrdtr: false
      read_timeout: 2
      write_timeout: 2

  - swpwm:
      name: "pwm-0"
      gpio: 7
      dutycycle: 0.5 # 50%
      frequency: 100 # hz

  - swpwm:
      name: "pwm-1"
      gpio: 10
      dutycycle: 0.5 # 50%
      frequency: 100 # hz

  - max31856:
      name: "max31856-0"
      tc_type: "T"
      dev: "spi-0"
      mode: 'automatic' # one-shot or automatic (this field not used for now)
      sample_avg: 1 # 1, 2, 4, 8, 16

  - max31865:
      name: "max31865-0"
      dev: "spi-1"

  - smoothie:
      name: "smoothie-0"
      dev: "uart-0"

  - extruder:
      name: "extruder-0"
      dev: "tcpuart-0"

services:

  output_sensor:
    enable: true
    scan_interval_ms: 1000
    dev: "max31856-0"

  tank_sensor:
    enable: true
    scan_interval_ms: 1000
    dev: "max31865-0"

  heater:
    enable: true
    scan_interval_ms: 1000
    dev: "pwm-0"
    P: 2
    I: 0.25
    D: 1

  refiller:
    enable: true
    scan_interval_ms: 1000
    dev: "pwm-1"

  brewer:
    enable: true
    moving_dev: "smoothie-0"
    extrude_dev: "extruder-0"
